# Set update schedule for GitHub Actions
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # For GitHub Actions '/' means .github/workflows/**/*.{yaml,yml}
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    assignees:
      - "krzysztofczyz-da"
      - "mblaze-da"
      - "martinflorian-da"
