repos:
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        args: ["--severity=warning"] # Optionally only show errors and warnings
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.10
    hooks:
      - id: actionlint
        args: ["-pyflakes=", "-shellcheck=shellcheck"] # Enable shellcheck integration and disable pyflakes integration
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-yaml
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: pin-github-actions
        name: Pin GitHub Actions versions
        description: Pin GHA action versions
        language: system
        entry: pin-github-action
        files: '^.github/workflows/'
        types: [yaml]
